name: inventory
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: inventory
    networks:
      - inventory
    volumes:
      - data:/opt/data:rw
    configs:
      - source: app_config
        target: /secrets/.env
    command: ["/opt/venv/bin/python", "/opt/application", "0.0.0.0", "8000"]
    restart: always

configs:
  app_config:
    file: ./configs/inventory.conf

volumes:
  data:
    name: "inventory-data"

networks:
  inventory:
    name: "inventory-net"