---
- name: Install {{ service_name|capitalize }} Microservice
  hosts: localhost
  remote_user: root
  vars:
    install_path: "/opt/{{ service_name }}"
    venv_path: "{{ install_path }}/venv"

  tasks:
  - name: Create Group
    group:
      state: present
      name: "{{ service_name }}"
      system: true
  - name: Create User
    user:
      state: present
      name: "{{ service_name }}"
      system: true
      group: "{{ service_name }}"
      shell: /bin/bash
      create_home: true
      home: "{{ install_path }}"
  - name: Python Virtual Env
    command:
      cmd: /opt/python/bin/python -m venv "{{ venv_path }}"
  - name: Ensure Poetry
    command:
      cmd: "{{ venv_path }}/bin/pip install poetry"
  - name: Install Dependencies
    command:
      cmd: "{{ venv_path }}/bin/poetry build"
  - name: Install Package
    command:
      cmd: "{{ venv_path }}/bin/pip install -e ."
  - name: Install Service
    template:
      src: systemd/inventory.service.j2
      dest: /etc/systemd/system/inventory.service
  - name: Enable Service
    systemd:
      state: started
      enabled: yes
      name: inventory


